### ISSUE TITLE
Migration to nix-community

### ISSUE THREAD

**Issue by nilp0inter** [nix-community/autofirma-nix#50]
This is an umbrella issue to keep track of all the necessary changes after the migration to the nix-community GitHub organization.

- [X] Update README to reflect the new repo URL. Closed via #49.
- [x] #51 
- [x] #53
- [x] Discuss how to inform users about the change in cache.
- [x] Push to nix-community's cache right away.
- [x] Update the README.
- [x] Open a pinned issue documenting the migration procedure.
- [x] Test that the new cache contains the derivations for all the supported branches.
- [x] Remove `autofirma-nix` cache to induce an error on the user side.

**Comment by nilp0inter** [comment]
Regarding the cache migration. We'll push to nix-community's cache right away, update the README and open a pinned issue documenting the migration procedure, and finally remove `autofirma-nix` cache to induce an error on the user side.
